### ISSUE TITLE
Upgrade to bootstrap 4

### ISSUE THREAD

**Issue by plus1319** [hamed-shirbandi/MvcPagedList.Core#1]
hi , thanks for your awesome package to share us , Can you upgrade package to bootstrap 4 because everyone use bootstrap 4 with dot net core 2 right now

**Comment by hamed-shirbandi** [comment]
Hi and thanks for your suggestion.
I will try to add a stand-alone style.css.

**Comment by coommark** [comment]
Was this ever done please?

**Comment by hamed-shirbandi** [comment]
sorry @coommark 
I will try to add this feature in this week
