### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by foladi** [hamed-shirbandi/MvcPagedList.Core#11]
Hello and thank you. The question that is at your service is that if we want to enclose each script page in MvcPagedList.Core after loading ajax, where should we proceed? Thank you.
قای شیربندی با سلام وتشکر سوالی که خدمتتان اینست که اگر بخواهیم در MvcPagedList.Core  بعد از لود ajax هر صفحه اسکریپتی را اچرا کنیم کجا باید اقدام کنیم.ممنون

**Comment by hamed-shirbandi** [comment]
Sorry to answer too late but maybe it will be used by someone.
You just need to use data-ajax html attribute in ajaxAttributes parameter.
Consider that you must replace '-' in the table below with '_' in the code.
So you can have something like this:

```

@PagedList.Pager(actionName: "search", controllerName: "home",areaName:"",
    routeValues: new
    {
        term = Context.Request.Query["term"],
        sortOrder = Context.Request.Query["sortOrder"],
        sortBy = Context.Request.Query["sortBy"],

    },
    ajaxAttributes: new 
    {
        data_ajax = "true",
        data_ajax_loading = "#global-ajax-loading",
        data_ajax_update = "#ajax-show-list",
        data_ajax_method = "GET",
        data_ajax_mode = "replace",

        //Add this line to call your js function  <<----------LOOK-----------
        data_ajax_success  = "MyFunction(data)"
        

    },
    pagerOptions: new PagerOptions
    {
        currentPage = (int)ViewBag.CurrentPage,
        PageCount = (int)ViewBag.PageSize,
        TotalItemCount = (int)ViewBag.TotalItemCount,
        DisplayMode = PagedListDisplayMode.IfNeeded,
        DisplayInfoArea = true,
        LinkToNextPageFormat = "next",
        LinkToPreviousPageFormat = "prev",
        CurrentLocationFormat = "page",
        PageCountFormat = "of",
        TotalItemCountFormat = "total count",
        GetStyleSheetFileFromCdn=true,
    } )

```
### data-ajax attributes
<table class="table table-striped table-hover table-bordered table-condensed top15 table100" style="max-width: 100%; width: auto; margin-left: auto; margin-right: auto;"> <tbody> <tr> <td> <b>&nbsp;HTML attribute<span>&nbsp;</span> </b> </td> <td> <b>&nbsp;AjaxOptions<span>&nbsp;</span> </b> </td> </tr> <tr> <td>&nbsp;data-ajax-confirm<span>&nbsp;</span> </td> <td>&nbsp;Confirm<span>&nbsp;</span> </td> </tr> <tr> <td>&nbsp;data-ajax-method<span>&nbsp;</span> </td> <td>&nbsp;HttpMethod<span>&nbsp;</span> </td> </tr> <tr> <td>&nbsp;data-ajax-mode<span>&nbsp;</span> </td> <td>&nbsp;InsertionMode<span>&nbsp;</span> </td> </tr> <tr> <td>&nbsp;data-ajax-loading-duration<span>&nbsp;</span> </td> <td>&nbsp;LoadingElementDuration<span>&nbsp;</span> </td> </tr> <tr> <td>&nbsp;data-ajax-loading<span>&nbsp;</span> </td> <td>&nbsp;LoadingElementId<span>&nbsp;</span> </td> </tr> <tr> <td>&nbsp;data-ajax-begin<span>&nbsp;</span> </td> <td>&nbsp;OnBegin<span>&nbsp;</span> </td> </tr> <tr> <td>&nbsp;data-ajax-complete<span>&nbsp;</span> </td> <td>&nbsp;OnComplete<span>&nbsp;</span> </td> </tr> <tr> <td>&nbsp;data-ajax-failure<span>&nbsp;</span> </td> <td>&nbsp;OnFailure<span>&nbsp;</span> </td> </tr> <tr> <td>&nbsp;data-ajax-success<span>&nbsp;</span> </td> <td>&nbsp;OnSuccess<span>&nbsp;</span> </td> </tr> <tr> <td>&nbsp;data-ajax-update<span>&nbsp;</span> </td> <td>&nbsp;UpdateTargetId<span>&nbsp;</span> </td> </tr> <tr> <td>&nbsp;data-ajax-url<span>&nbsp;</span> </td> <td>&nbsp;Url<span>&nbsp;</span> </td> </tr> </tbody> </table>
