### ISSUE TITLE
Seo friendly

### ISSUE THREAD

**Issue by kaktoosii** [hamed-shirbandi/MvcPagedList.Core#2]
سلام من کد هاتون رو دیدم ولی سوالی که دارم اینه که صفحه بندی به این شکل به نظر سئوی خوبی نداره
راهی هست که بشه آدرس بار هم تغییر داد 
با کلیک روی صفحه ها

**Comment by hamed-shirbandi** [comment]
کافیه برای پارامتر ajaxAttributes مقدار null رو ارسال کنین یا data_ajax رو false کنین
لطفا انتهای فایل readme رو مجددا مطالعه کنین

**Comment by kaktoosii** [comment]
ممنونم منظورم این نیست که کلا ایجکس غیر فعال بشه منظورم این بود تو حالت ایجکسی آدرس بار هم تغیر کنه
یعنی  push state
