### ISSUE TITLE
Problem with display options

### ISSUE THREAD

**Issue by pawelPriv** [hamed-shirbandi/MvcPagedList.Core#21]
I develop Asp .Net 6  application in Visual Studio 2022.
When I use on my view  below Pager code without  display options everything works fine (Pager is visible and included in html body):

        @PagedList.Pager(actionName: "SettlementsGrid",

        pagerOptions: new PagerOptions
        {
        //DisplayInfoArea=false,
        currentPage = Model.PageIndex,
        PageCount = 20,
        TotalItemCount = Model.RowsCount
        },       
        controllerName: "Settlements",
        ajaxAttributes: new
            {
            data_ajax = "true",
            data_ajax_loading = "#ajaxSpinner2",
            data_ajax_update = "#A_divSettlementsGrid",
            data_ajax_method = "GET",
            data_ajax_mode = "replace",            
            }

        )

When I try to uncomment display option Pager is not build in html body and it is not visible. I do net get any error during rendering of view.

**Comment by hamed-shirbandi** [comment]
Hello @pawelPriv,
Sorry for the late response.
I found the bug and fixed it.
A new NuGet package is released ([version 3.2.0](https://www.nuget.org/packages/MvcPagedList.Core/3.2.0)).
Thanks for your contribution.
