### ISSUE TITLE
maximum page number to display

### ISSUE THREAD

**Issue by orangesoncom** [hamed-shirbandi/MvcPagedList.Core#22]
Hi,

is there a way to display the maximum pages displayed? so the page only displays "n" pages according to what we need, because if there are 100 pages it will make the pages **1-100**, what I want is **[1]**,**[2]**,**[3]**,**[4]**,**[5 ]****,[...]**,**[last]** if I set the maximum pages displayed is 5, sorry for my English and thank you for this amazing project

**Comment by hamed-shirbandi** [comment]
Hey @orangesoncom,

So sorry for responding too late. I was not able to work on my open source projects for a while.
Unfortunately, this feature is not supported.
I thought maybe the current approach, using a horizontal scroll, is a better solution to handle the pagination in case we have too many pages. So, you don't have to make too many requests to find a page. You just scroll and find it.

Please let me know if you still think having a maximum page number limitation is still needed.

Thanks.
